services:
  mongo:
    image: mongo:6.0
    container_name: coinly-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: coinly-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:example@mongo:27017/coinly?authSource=admin
    depends_on:
      - mongo

  frontend:
    build: ./frontend   # uses the production Dockerfile by default
    container_name: coinly-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
