version: "3.9"

services:
  backend:
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev   # assumes you added a "dev" script with nodemon

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev   # Vite or CRA dev server
    ports:
      - "5173:5173"        # expose vite dev port
